#Soubor: Makefile
#Datum: Duben 2017
#Autor: Marek Kukucka, xkukuc04@stud.fit.vutbr.cz
#Projekt: 2.Uloha
#Popis: Makefile pro prelozeni souboru proj2.c

all:
	gcc proj2.c -o proj2 -std=gnu99 -Wall -Wextra -Werror -pedantic -lpthread
